{{- if .Values.worker.pdb.enabled }}
# PodDisruptionBudget for worker.
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "moiraweave.worker.fullname" . }}-pdb
  labels:
    {{- include "moiraweave.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  minAvailable: {{ .Values.worker.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "moiraweave.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
{{- end }}
