blank_issues_enabled: false
contact_links:
  - name: Discussions (Q&A)
    url: https://github.com/jgallego9/inferflow-mlops/discussions
    about: Please ask usage and architecture questions in Discussions.
