apiVersion: v1
kind: Service
metadata:
  name: {{ include "moiraweave.apiGateway.fullname" . }}
  labels:
    {{- include "moiraweave.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
    - port: {{ .Values.apiGateway.service.port }}
      targetPort: {{ .Values.apiGateway.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "moiraweave.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
