"""Pydantic v2 schemas for messages that flow through Redis Streams.

Using ``model_validate`` on the producer side guarantees the dict written to
the stream always satisfies the schema; ``model_validate`` on the consumer
side raises ``ValidationError`` on malformed messages instead of propagating
``None`` / empty strings deeper into the pipeline.
"""

from typing import Literal

from pydantic import BaseModel


class TranscribeStreamMessage(BaseModel):
    """Payload written to the Redis Stream for a transcription job.

    :param job_id: UUID generated by api-gateway.
    :param type: Discriminator field — always ``"transcribe"``.
    :param audio_url: URL of the audio file to transcribe (str, already validated).
    :param language: BCP-47 language code or ``"auto"``.
    :param user: Subject claim of the requesting user (for access control).
    """

    job_id: str
    type: Literal["transcribe"] = "transcribe"
    audio_url: str
    language: str = "auto"
    user: str
